name: snapshot

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snapshot:
    runs-on:
      # Use our own large runners with more CPU and RAM for faster builds
      group: releasers
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "nightly"
          distribution: goreleaser-pro
          args: build --snapshot --clean
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
